### ISSUE TITLE
script is not running properly

### ISSUE THREAD

**Issue by skhaneshenas** [samsoon-inayat/string_pulling_mouse_matlab#1]
Hello,

I am trying to use the string_pulling_mouse matlab script for kinematic analysis of animal grasp task video but
once I run the script an empty GUI window opens with no Messages section where I can select the video file.
I tried Matlab 2017 and higher versions in both Linux and windows systems but I had the same problem.

What would you recommend to solve the problem.

Best,
Sona

**Comment by samsoon-inayat** [comment]
The problem was that in Windows Display Settings, zoom was set to 125%. When set to 100%, the GUI window displayed fine.
Thank you Sona for reporting this problem and also finding the solution.
